/**
 * T027 — "Get test tokens" faucet button (FR-014a): drives `TestToken.faucet()`
 * through the shared `useTxStatus` state machine (FR-022: pending → confirmed |
 * failed, terminal state visible until acknowledged).
 *
 * Addresses and ABI come from `contracts/index.ts` (generated by the deploy
 * script) — never hardcoded. Failures are decoded to friendly sentences
 * (FR-017): users never see raw revert data (e.g. `FaucetCooldown()`).
 */
import { useEffect } from 'react';
import { useWaitForTransactionReceipt, useWriteContract } from 'wagmi';
import { abiFor, activeChainId, contractAddress, isDeployed } from '../contracts';
import { useEnsureChain } from '../hooks/useEnsureChain';
import { useTxStatus } from '../hooks/useTxStatus';
import { Button } from './primitives/Button';
import { TxStatus } from './states/TxStatus';
import { WrongNetworkPrompt } from './states/WrongNetworkPrompt';

export function FaucetButton() {
  const { state, onSubmitted, onConfirmed, onFailed, acknowledge, isPending } = useTxStatus(
    'faucet',
  );
  const { ensureChain } = useEnsureChain();
  const {
    writeContract,
    data: hash,
    isPending: signing,
    error: writeError,
  } = useWriteContract();
  const { data: receipt, error: receiptError } = useWaitForTransactionReceipt({ hash });

  // hash → pending (submitted), receipt → confirmed, errors → failed.
  // Callbacks from useTxStatus are stable, so deps only change on real events.
  useEffect(() => {
    if (hash) onSubmitted('faucet', hash);
  }, [hash, onSubmitted]);
  useEffect(() => {
    if (receipt) onConfirmed();
  }, [receipt, onConfirmed]);
  useEffect(() => {
    if (writeError) onFailed(writeError);
  }, [writeError, onFailed]);
  useEffect(() => {
    if (receiptError) onFailed(receiptError);
  }, [receiptError, onFailed]);

  const tokenAddress = contractAddress(activeChainId, 'TestToken');
  const busy = signing || isPending;
  const terminal = state.status === 'confirmed' || state.status === 'failed';

  const claim = async () => {
    if (!tokenAddress) return;
    // T048/T050: blocked on the wrong chain; proceeds only after a
    // successful switchChain. The prompt below explains the block.
    if (!(await ensureChain())) return;
    writeContract({
      address: tokenAddress as `0x${string}`,
      abi: abiFor('TestToken'),
      functionName: 'faucet',
    });
  };

  return (
    <div className="flex flex-wrap items-center gap-3">
      <WrongNetworkPrompt className="w-full" />
      <Button
        type="button"
        onClick={() => void claim()}
        busy={busy}
        disabled={!tokenAddress || !isDeployed(activeChainId)}
      >
        Get test tokens
      </Button>
      <TxStatus state={state} />
      {state.status === 'failed' && state.error ? (
        <p role="alert" className="text-sm text-ink/80">
          {state.error}
        </p>
      ) : null}
      {terminal ? (
        <Button type="button" variant="secondary" onClick={acknowledge}>
          Dismiss
        </Button>
      ) : null}
    </div>
  );
}
